---
title: "CCVI Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#### Set Up Needed for Documents ####
library(tidyverse)
library(readxl)
library(knitr)
library(here)
library(kableExtra)
library(dplyr)
library(xtable)

setwd("P:/Conservation Programs/Natural Heritage Program/PNHP_CCVI/CCVI_automation")

url_CCVIpage <- "http://www.naturalheritage.state.pa.us/climate.aspx" #CCVI website

## Loading in excels ##
ccvi_file <- "P://Conservation Programs/Natural Heritage Program/PNHP_CCVI/CCVI_automation/ccvi_release_3.02_Master.xlsm" #master excel for CCVI
ccvi_info <- "P://Conservation Programs/Natural Heritage Program/PNHP_CCVI/CCVI_automation/CCVI Life History Data Hub.xlsx" #Habitat excel
ccvi_threats <- "P://Conservation Programs/Natural Heritage Program/PNHP_CCVI/CCVI_automation/CompiledELCODE_threatsrecs_June2022.xlsx" #threats excel
ccvi_images <- "P://Conservation Programs/Natural Heritage Program/PNHP_CCVI/CCVI_automation/Image citations.xlsx" #image citation excel
colnames_new <- read.csv("P://Conservation Programs/Natural Heritage Program/PNHP_CCVI/CCVI_automation/ccvicolnames.csv") #full column names

ccvi <- read_xlsx(ccvi_file, "Results Table", range=cell_rows(6:150)) #reading in ccvi excel
ccvi_info <- read_xlsx(ccvi_info) #reading in habitats excel
ccvi_threats_headings <- as.character(read_xlsx(ccvi_threats,n_max=1,col_names = FALSE))[1:25] #reading in threats headings (separate in order to skip over unneeded cells)
ccvi_threats <- read_xlsx(ccvi_threats,col_names = ccvi_threats_headings,range=cell_rows(873:2500)) #reading in threats excel
ccvi_images <- read_xlsx(ccvi_images, "Species Images") #reading in images excel

## Renaming and adding column and heading names##
colnames(ccvi_info)[1] = "SNAME" #renaming species column to SNAME (for matching purposes)
colnames(ccvi) <- colnames_new$nameNew #renaming column names in ccvi

## Filtering out/editing vulnerability factors and comments ##
ccvi.factors <- read_xlsx(ccvi_file,"Results Table",
                          range=cell_rows(3:5)) #headings of ccvi
ccvi.factors = as.character(ccvi.factors[1,]) #collecting factors
comment.col = which(ccvi.factors == "Comments") #comment columns
factor.col = comment.col-1 #factor columns
factor.full.name = c("Sea Level","Natural Barriers","Anthropogenic Barriers","Climate Change Mitigation","Dispersal/Movement","Historical Thermal Niche","Physiological Thermal Niche","Historical Hydrological Niche","Physiological Hydrological Niche","Specific Disturbance Regime","Ice/Snow Dependence","Physical Habitat Restrictions","Dependence on Other Species for Habitat","Diet","Pollinators","Other Interspecific Disperal","Pathogens or Natural Enemies","Competition Sensitivity","Other Interspecific Interactions","Measured Genetic Variation","Recent Genetic Bottlenecks","Reproductive System","Phenological Responses","Documented Response to Climate Change","Modeled Future Change in Population or Range Size","Modeled Overlap of Future with Current Range","Occurence of Protected Areas in Modeled Future Distribution") #full names of CC factors
ccvi.factors[factor.col] = factor.full.name #renaming factors

## Dealing with changed names for BONAP maps ##
bonap.changed.names = c("Carex paupercula","Marshallia pulchra",
                        "Primula meadia", "Viburnum trilobum",
                        "Viola appalachiensis") #species w/ different BONAP names
bonap.alt.names = c("Carex magellanica ssp irrigua","Marshallia grandiflora",
                    "Dodecatheon meadia","Viburnum opulus var americanum",
                    "Viola walteri var appalachiensis") #alternative BONAP names

## Setting up Vulernability Index Table ##
db_ccvi_code <- c("EV","HV","MV","LV","IE") #vulnerability code
db_ccvi_name <- c("Extremely Vulnerable (EV)","Highly Vulnerable (HV)","Moderately Vulnerable (MV)","Not Vulnerable/Presumed Stable (LV)","Not Vulnerable/Increase Likely (IE)") #vulnerability name
db_ccvi_desc <- c("Abundance and/or range extent within geographical area assessed extremely likely to substantially decrease or disappear by 2050.","Abundance and/or range extent within geographical area assessed likely to decrease significantly by 2050.","Abundance and/or range extent within geographical area assessed likely to decrease by 2050.","Available evidence does not suggest that abundance and/or range extent within the geographic area assessed will change (increase/decrease) substantially by 2050. Actual range boundaries may change.","Available evidence suggests that abundance and/or range extent within geographic area assessed is likely to increase by 2050.") #vulnerability description
db_ccvi_col <- c("RedOrange","BurntOrange","Goldenrod","Green","Gray") #vulnerability color

db_ccvi <- data.frame(code=db_ccvi_code, name=db_ccvi_name, description=db_ccvi_desc, color=db_ccvi_col, stringsAsFactors=FALSE) #combining vulnerability info into dataframe
rm(db_ccvi_code, db_ccvi_name, db_ccvi_desc, db_ccvi_col) #removing objects

```

```{r}
#### Produces documents ####

setwd("P:/Conservation Programs/Natural Heritage Program/PNHP_CCVI/CCVI_automation/PDFs") #setting working directory to where I want pdfs to go

for(i in 1:nrow(ccvi)){
  abr.sname = unlist(strsplit(ccvi$SNAME[i]," var. "))[1] #Removes var. from name (done for matching purposes)
  spec.pictures = list.files(path="P://Conservation Programs/Natural Heritage Program/PNHP_CCVI/CCVI_automation/CCVI Plant Images") #lists names of images
  sep.names = unlist(strsplit(abr.sname,split=" +")) #separates words of species name
  grep.name = paste0(sep.names[1],".*",sep.names[2],"|",tolower(sep.names[1]),".*",sep.names[2]) #pastes .* between words in order to find images with both names (accounting for _, -, spaces, etc)
  spec.image = grep(grep.name,spec.pictures,value=TRUE) #finds image matching species name
  image.citation = if(is.element(abr.sname,ccvi_images$Species)==TRUE){ #finding if the species is in the images dataframe
    image.index = which(ccvi_images$Species == abr.sname) #row of species
    ccvi_images$Citation[image.index] #pulls citation of image
  } else {
    "Pennsylvania Natural Heritage Program" #If image is not in dataframe
  }
  bonap.maps = list.files(path="W://Heritage/Heritage_Projects/1495_PlantConservationPlan/BONAP/Maps") #lists names of maps
  if(is.element(abr.sname,bonap.changed.names)==TRUE){ #checks for specific species that have name change
    bonap.disclaimer = "Note: The Pennsylvania Natural Heritage Program is currently updating its taxonomic standard, which sometimes recognizes different names than what is used in BONAP (the source of the range maps)." #disclaimer for different BONAP names
    name.index = which(bonap.changed.names==abr.sname) #index of species
    abr.alt.name = bonap.alt.names[name.index] # identifying new name
    sep.names = unlist(strsplit(abr.alt.name,split=" +")) #splitting up names
    if(length(sep.names)==4){ # for species with var., spp., etc
      bonap.grep = paste0(sep.names[1],".*",sep.names[2],".*",sep.names[3],".*",sep.names[4]) #pasting names together with .* to help matching
    } else { #species with no connector
      bonap.grep = paste0(sep.names[1],".*",sep.names[2]) 
    }
  } else { # same for the normal species
    bonap.disclaimer = ""
    abr.sname = unlist(strsplit(ccvi$SNAME[i]," var. "))
    sep.names = unlist(strsplit(abr.sname,split=" +"))
    if(length(sep.names)==3){
      bonap.grep = paste0(sep.names[1],"_",sep.names[2],"_var_",sep.names[3])
    } else {
      bonap.grep = paste0(sep.names[1],"_",sep.names[2])
    }
  }
  range.map = grep(bonap.grep,bonap.maps,value=TRUE) #finds map matching species name
  if(is_empty(range.map) == TRUE){ #creating disclaimer for missing BONAP map
    missing.map.note = "Range map currently unavailable: Species distribution is still under review due to taxonomic uncertainties."
  } else {
    missing.map.note = ""
  }
  habitat.row = grep(abr.sname,ccvi_info$SNAME) #finds rows of species
  habitat = as.character(ccvi_info[habitat.row,"Habitat"]) #habitat
  threats.row = grep(abr.sname,ccvi_threats$SNAME) #finds rows of species
  all.threats = as.vector(unlist(ccvi_threats[threats.row,9])) #all threats
  ccvi.descr = grepl("__Insert Species Name Here__",all.threats) #finding ccvi descriptions in threat list
  threats.list = all.threats[!ccvi.descr] #removing ccvi descr
  missing.threats = is.na(threats.list) #finding NA (no threat assigned)
  threats.list = threats.list[!missing.threats] #removing NAs
  latex.sub.threats = gsub("%","\\\\%",threats.list) #adding in \ (escape character) before any % (done for latex purposes since % is the comment character)
  threats = if(length(latex.sub.threats)==0|length(threats.row)==0){ #finding when there are no threats associated or species missing
    "Threats other than climate change impacts to this species are largely unknown." #filler phrase for unknown threats
  } else {
    latex.sub.threats #produces filtered threats list
  }
  si = grep("-*SI-*",ccvi[i,]) #finding somewhat increase factors
  gi = grep("-*GI-*",ccvi[i,]) # finding greatly increase factors
  inc = grep("-*Inc-*",ccvi[i,]) #finding increasing factors
  comb.fact.all = c(gi,inc,si) #combining factors
  comb.fact = intersect(comb.fact.all,factor.col) #making sure matched phrases are actually factors (done since "Inc" is in some comments)
  comm = unique(comb.fact)+1 #comments associated with factors
  factor.comm = as.vector(unlist(ccvi[i,comm])) #producing comments
  factors = ccvi.factors[comb.fact] #producing factors
  factor.table = data.frame("Factors"=factors,"Details"=factor.comm) #making table of factors/comments
  rownames(factor.table) = NULL #removing numbered rows
  factor.table.latex = 
    xtable(factor.table,align=c("l","|p{0.275\\textwidth}|","p{0.7\\textwidth}|")) #making latex friendly table 
  bold.center <- function(x) {paste('{\\textbf{\\centerline{',x,'}}}', 
                                    sep ='')} #bold/centering function
  factor.table.latex = print(factor.table.latex, 
                             include.rownames = FALSE,
                             hline.after = c(-1:(nrow(factor.table)-1)),
                             sanitize.colnames.function=bold.center,
                             tabular.environment="longtable") #creates latex script
  fname <- stringi::stri_replace_all_fixed(ccvi$SNAME[i], " ", "_") #file names of species
  pdf_filename <- paste(fname,"_",gsub("[^0-9]", "", Sys.Date() ),sep="") #adding date to name
  makePDF <- function(rnw_template) { #pdf making function
    knit(here::here("ccvi_summary.Rnw"), 
         output=paste(pdf_filename, ".tex",sep=""))
    call <- paste0("xelatex -interaction=nonstopmode ",pdf_filename, ".tex")
    system(call)
    system(call) # 2nd run to apply page numbers
  }
  # function to delete .txt, .log etc if pdf is created successfully.
  deletepdfjunk <- function(pdf_filename){
    fn_ext <- c(".aux",".out",".run.xml",".bcf",".blg",
                ".tex",".log",".bbl",".toc")
    if (file.exists(paste(pdf_filename, ".pdf",sep=""))){
      for(i in 1:NROW(fn_ext)){
        fn <- paste(pdf_filename, fn_ext[i],sep="")
        if (file.exists(fn)){
          file.remove(fn)
        }
      }
    }
  }
  makePDF(ccvi_summary.Rnw) #making species pdf
  deletepdfjunk(pdf_filename) #removing excess files 
}
  
setwd(here::here()) #restoring original working directory

```



